class _BotCommands:
    def __init__(self):
        self.StartCommand = 'dstart'
        self.MirrorCommand = 'dmirror'
        self.UnzipMirrorCommand = 'dunzipmirror'
        self.TarMirrorCommand = 'dtarmirror'
        self.CancelMirror = 'dcancel'
        self.CancelAllCommand = 'dcancelall'
        self.ListCommand = 'dlist'
        self.StatusCommand = 'dstatus'
        self.AuthorizeCommand = 'dauthorize'
        self.UnAuthorizeCommand = 'dunauthorize'
        self.AuthListCommand = 'dauthlist'
        self.PingCommand = 'dping'
        self.RestartCommand = 'drestart'
        self.StatsCommand = 'dstats'
        self.HelpCommand = 'dhelp'
        self.LogCommand = 'dlog'
        self.SpeedCommand = 'dspeedtest'
        self.CloneCommand = 'dclone'
        self.WatchCommand = 'dwatch'
        self.TarWatchCommand = 'dtarwatch'
        self.DeleteCommand = 'ddel'
        self.UsageCommand = 'dusage'
        self.RepoCommand = 'drepo'

BotCommands = _BotCommands()
